### ISSUE TITLE
Splash Screen Issue for Androd version < 6

### ISSUE THREAD

**Issue by Zoham** [NeuromancersIITBBS/InstiApp#31]
Splash Screen stretched for Android Lollipop
Android 5.1
Samsung Galaxy S4

![screenshot_2019-01-13-21-22-55](https://user-images.githubusercontent.com/20607448/51087461-bf54d400-1779-11e9-8020-858a64ce461c.png)

**Comment by Zoham** [comment]
Also change the splash screen image - preferred with white text

**Comment by vatch123** [comment]
This seems to be resolved in #47 , this issue should be closed?
