### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by JatinKhare** [NeuromancersIITBBS/InstiApp#35]
Circular progress bar to be replaced by horizontal.

**Comment by JatinKhare** [comment]
Progress bar at the time of loading the data from the firebase.

**Comment by Zoham** [comment]
1. Progress Bar has some default padding on top and bottom. Try to get rid of it.
2. Unify erp progress bar and app bar main progress bar

**Comment by JatinKhare** [comment]
Ok.

**Comment by vatch123** [comment]
This issue seems to be resolved in the pr #47
